version: '3.11'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: deployments/compose/django/Dockerfile
    image: django_web
    command: /start
    volumes:
      - .:/app
    ports:
      - '8024:8000'
    env_file:
      - envs/.env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ticket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1253'
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: deployments/compose/bot/Dockerfile
    command: python apps/bot/main.py
    volumes:
      - .:/app
    depends_on:
      - web
    restart: always

  redis:
    restart: always
    image: redis

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15674:15672'
    volumes:
        - rabbitmq:/var/lib/rabbitmq

  celery_worker:
    build:
      context: .
      dockerfile: ./deployments/compose/django/Dockerfile
    image: celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - envs/.env
    depends_on:
      - redis
      - rabbitmq
      - db


volumes:
  pg_data:
  rabbitmq: