version: '3.11'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: deployments/compose/django/Dockerfile
    image: django_web
    command: /start
    volumes:
      - .:/app
    ports:
      - '8024:8000'
    env_file:
      - envs/.env
    depends_on:
      - db
    networks:
      - ticket_net

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ticket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1253'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ticket_net

  bot:
    build:
      context: .
      dockerfile: deployments/compose/bot/Dockerfile
    command: python apps/bot/main.py
    volumes:
      - .:/app
    depends_on:
      - web
    restart: on-failure
    networks:
      - ticket_net

volumes:
  pg_data:

networks:
  ticket_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16