version: '3.11'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: deployments/compose/django/Dockerfile
    image: django_web
    command: /start
    volumes:
      - .:/app
    ports:
      - ${PORT:-8001}:8000
    env_file:
      - envs/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ticket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1253'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: deployments/compose/bot/Dockerfile
    command: python apps/bot/main.py
    volumes:
      - .:/app
    depends_on:
      - web
    restart: on-failure


volumes:
  postgres_data:
