# Generated by Django 5.0.8 on 2024-09-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Foydalanuvchi nomi",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ism"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Familiya"
                    ),
                ),
                (
                    "phone",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Telefon raqam"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("uz", "O'zbek tili"),
                            ("ru", "Rus tili"),
                            ("en", "Ingliz tili"),
                        ],
                        max_length=10,
                        verbose_name="Til",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faolmi")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("user", "Foydalanuvchi"),
                        ],
                        default="user",
                        max_length=10,
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Foydalanuvchisi",
                "verbose_name_plural": "Bot Foydalanuvchilari",
                "db_table": "bot_users",
            },
        ),
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nomi"),
                ),
                ("description", models.TextField(verbose_name="Tavsif")),
                ("start_date", models.DateField(verbose_name="Boshlanish sanasi")),
                ("end_date", models.DateField(verbose_name="Tugash sanasi")),
                ("time", models.TimeField(verbose_name="Vaqt")),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="Eng arzon narx"
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="Eng qimmat narx"
                    ),
                ),
                ("photo", models.ImageField(upload_to="concerts", verbose_name="Rasm")),
                (
                    "thumbnail",
                    models.ImageField(upload_to="concerts", verbose_name="Mini rasm"),
                ),
            ],
            options={
                "verbose_name": "Konsert",
                "verbose_name_plural": "Konsertlar",
                "db_table": "concert",
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nomi"),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="O'tish joyi")),
                ("location", models.URLField(max_length=255, verbose_name="Lokatsiya")),
                ("address", models.CharField(max_length=255, verbose_name="Manzil")),
            ],
            options={
                "verbose_name": "Zal",
                "verbose_name_plural": "Zallar",
                "db_table": "hall",
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nomi"),
                ),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Telefon raqam"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("location", models.URLField(max_length=255, verbose_name="Lokatsiya")),
                ("address", models.CharField(max_length=255, verbose_name="Manzil")),
            ],
            options={
                "verbose_name": "Ma'lumot",
                "verbose_name_plural": "Ma'lumotlar",
                "db_table": "info",
            },
        ),
        migrations.CreateModel(
            name="ConcertSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="Sotilganmi"),
                ),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.concert",
                        verbose_name="Konsert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konsert joyi",
                "verbose_name_plural": "Konsert joylari",
                "db_table": "concert_seat",
            },
        ),
        migrations.CreateModel(
            name="Donate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Telefon raqam"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="Summa"
                    ),
                ),
                ("message", models.TextField(verbose_name="Xabar")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.botusers",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xayriya",
                "verbose_name_plural": "Xayriyalar",
                "db_table": "donate",
            },
        ),
        migrations.AddField(
            model_name="concert",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ticket.hall",
                verbose_name="Konsert zal",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ticket.concert"
                    ),
                ),
                ("concert_seats", models.ManyToManyField(to="ticket.concertseat")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.botusers",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                ("row", models.PositiveIntegerField(verbose_name="Qator")),
                ("seat_number", models.PositiveIntegerField(verbose_name="Joy raqami")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="Narx"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.hall",
                        verbose_name="Zal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Joy",
                "verbose_name_plural": "Joylar",
                "db_table": "seat",
            },
        ),
        migrations.AddField(
            model_name="concertseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ticket.seat",
                verbose_name="Joy",
            ),
        ),
    ]
