# Generated by Django 5.0.8 on 2024-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="concerts", verbose_name="Mini rasm"
            ),
        ),
    ]
