# Generated by Django 5.0.8 on 2024-09-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botusers",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ism va Familiya"
            ),
        ),
    ]
