# Generated by Django 5.0.8 on 2024-09-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donate",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="To'landi"),
        ),
    ]
