# Generated by Django 5.0.8 on 2024-09-23 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_alter_concert_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concert",
            old_name="start_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="concert",
            name="end_date",
        ),
        migrations.AddField(
            model_name="concert",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Sarlavha",
            ),
            preserve_default=False,
        ),
    ]
