# Generated by Django 5.0.8 on 2024-10-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_botusers_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("content", models.TextField(verbose_name="Maqola")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news/", verbose_name="Rasm"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
                "db_table": "news",
            },
        ),
    ]
