# Generated by Django 5.0.8 on 2024-09-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
