# Generated by Django 5.0.8 on 2024-09-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_ticket_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket",
            field=models.ImageField(upload_to="tickets/"),
        ),
    ]
