# Generated by Django 5.0.8 on 2024-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0004_remove_order_concert_seats_remove_concert_hall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Ism va Familiya"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="Tasdiqlandi"),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Telefon raqam"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="concert",
            name="date",
            field=models.DateField(verbose_name="Sanasi"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
    ]
