# Generated by Django 5.0.8 on 2024-10-05 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_alter_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="info",
            name="address",
        ),
        migrations.RemoveField(
            model_name="info",
            name="address_ru",
        ),
        migrations.RemoveField(
            model_name="info",
            name="address_uz",
        ),
        migrations.RemoveField(
            model_name="info",
            name="email",
        ),
        migrations.RemoveField(
            model_name="info",
            name="location",
        ),
        migrations.AddField(
            model_name="concert",
            name="map",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="concerts/map",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png"]
                    )
                ],
                verbose_name="Karta",
            ),
        ),
    ]
