# Generated by Django 5.0.8 on 2024-10-05 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_remove_info_address_remove_info_address_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="map",
            field=models.ImageField(
                blank=True,
                default="/static/images/404.png",
                null=True,
                upload_to="concerts/map",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png"]
                    )
                ],
                verbose_name="Karta",
            ),
        ),
    ]
