# Generated by Django 5.0.8 on 2024-09-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0005_order_full_name_order_is_confirmed_order_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="username",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Telegram username"
            ),
            preserve_default=False,
        ),
    ]
