# Generated by Django 5.0.8 on 2024-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_alter_ticket_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_id_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
