# Generated by Django 5.0.8 on 2024-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0006_info_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="To'landi"),
        ),
    ]
