# Generated by Django 5.0.8 on 2024-09-25 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0007_order_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donate",
            name="message",
        ),
        migrations.RemoveField(
            model_name="donate",
            name="phone",
        ),
    ]
