# Generated by Django 5.0.8 on 2024-09-26 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0008_remove_donate_message_remove_donate_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="photo",
            field=models.ImageField(
                upload_to="concerts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png"]
                    )
                ],
                verbose_name="Rasm",
            ),
        ),
    ]
