# Generated by Django 5.0.8 on 2024-10-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0009_seattype_name_ru_seattype_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusers",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("uz", "O'zbek tili"),
                    ("ru", "Rus tili"),
                    ("en", "Ingliz tili"),
                ],
                default="uz",
                max_length=10,
                verbose_name="Til",
            ),
        ),
    ]
