# Generated by Django 5.0.8 on 2024-09-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0009_alter_concert_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="address_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Manzil"),
        ),
        migrations.AddField(
            model_name="concert",
            name="address_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Manzil"),
        ),
        migrations.AddField(
            model_name="concert",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="concert",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="concert",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Nomi"
            ),
        ),
        migrations.AddField(
            model_name="concert",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Nomi"
            ),
        ),
        migrations.AddField(
            model_name="concert",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="concert",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Sarlavha"),
        ),
        migrations.AddField(
            model_name="info",
            name="address_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Manzil"),
        ),
        migrations.AddField(
            model_name="info",
            name="address_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Manzil"),
        ),
        migrations.AddField(
            model_name="info",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="info",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="info",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Nomi"
            ),
        ),
        migrations.AddField(
            model_name="info",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Nomi"
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
        migrations.AddField(
            model_name="seat",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
    ]
