# Generated by Django 5.0.8 on 2024-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MerchantTransactionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.CharField(max_length=255, null=True)),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Order ID"
                    ),
                ),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="Amount"),
                ),
                (
                    "time",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Time"),
                ),
                (
                    "perform_time",
                    models.BigIntegerField(
                        default=0, null=True, verbose_name="Perform Time"
                    ),
                ),
                (
                    "cancel_time",
                    models.BigIntegerField(
                        default=0, null=True, verbose_name="Cancel Time"
                    ),
                ),
                (
                    "state",
                    models.IntegerField(default=1, null=True, verbose_name="State"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Reason"
                    ),
                ),
                (
                    "created_at_ms",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Created At MS",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Merchant Transaction",
                "verbose_name_plural": "Merchant Transactions",
            },
        ),
    ]
