# Generated by Django 5.0.8 on 2024-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivmi"),
                ),
                ("order_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PROCESSING",
                        max_length=100,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                            ("OCTO", "OCTO"),
                            ("CASH", "Cash"),
                        ],
                        default="PAYME",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DONATE", "Donate"), ("ORDER", "Order")],
                        max_length=100,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payment",
            },
        ),
    ]
