# Generated by Django 5.0.8 on 2024-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktivmi"),
        ),
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("DONATE", "Donate"), ("ORDER", "Order")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan vaqti"),
        ),
    ]
