# Generated by Django 5.0.8 on 2024-10-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.BigIntegerField(verbose_name="Amount in cents"),
        ),
    ]
